# Generated by kpex 0.2.5
crashbackups stop
drc off
gds read /foss/designs/PROJECTS/cmos-pll-ihp-sg13g2/Combined_Design/design_data/gds/freq_div_cell.gds
load freq_div_cell
select top cell
flatten freq_div_cell_flat
load freq_div_cell_flat
cellname delete freq_div_cell -noprompt
cellname rename freq_div_cell_flat freq_div_cell
select top cell
extract path /foss/designs/PROJECTS/cmos-pll-ihp-sg13g2/Combined_Design/design_data/pex/freq_div_cell__freq_div_cell/magic_RC
extract do resistance
extract all
ext2sim labels on
ext2sim
extresist tolerance 1
extresist all
ext2spice short none
ext2spice merge none
ext2spice cthresh 0.01
ext2spice rthresh 100
ext2spice extresist on
ext2spice subcircuits top on
ext2spice format ngspice
ext2spice -p /foss/designs/PROJECTS/cmos-pll-ihp-sg13g2/Combined_Design/design_data/pex/freq_div_cell__freq_div_cell/magic_RC -o /foss/designs/PROJECTS/cmos-pll-ihp-sg13g2/Combined_Design/design_data/pex/freq_div_cell__freq_div_cell/magic_RC/freq_div_cell.pex.spice
quit -noprompt
