# Generated by kpex 0.2.5
crashbackups stop
drc off
gds read /foss/designs/PROJECTS/cmos-pll-ihp-sg13g2/Combined_Design/design_data/gds/half_add.gds
load half_add
select top cell
flatten half_add_flat
load half_add_flat
cellname delete half_add -noprompt
cellname rename half_add_flat half_add
select top cell
extract path /foss/designs/PROJECTS/cmos-pll-ihp-sg13g2/Combined_Design/design_data/pex/half_add__half_add/magic_RC
extract do resistance
extract all
ext2sim labels on
ext2sim
extresist tolerance 1
extresist all
ext2spice short none
ext2spice merge none
ext2spice cthresh 0.01
ext2spice rthresh 100
ext2spice extresist on
ext2spice subcircuits top on
ext2spice format ngspice
ext2spice -p /foss/designs/PROJECTS/cmos-pll-ihp-sg13g2/Combined_Design/design_data/pex/half_add__half_add/magic_RC -o /foss/designs/PROJECTS/cmos-pll-ihp-sg13g2/Combined_Design/design_data/pex/half_add__half_add/magic_RC/half_add.pex.spice
quit -noprompt
