# Generated by kpex 0.2.5
crashbackups stop
drc off
gds read /foss/designs/PROJECTS/cmos-pll-ihp-sg13g2/Combined_Design/design_data/gds/dff_nclk.gds
load dff_nclk
select top cell
flatten dff_nclk_flat
load dff_nclk_flat
cellname delete dff_nclk -noprompt
cellname rename dff_nclk_flat dff_nclk
select top cell
extract path /foss/designs/PROJECTS/cmos-pll-ihp-sg13g2/Combined_Design/design_data/pex/dff_nclk__dff_nclk/magic_RC
extract do resistance
extract all
ext2sim labels on
ext2sim
extresist tolerance 1
extresist all
ext2spice short none
ext2spice merge none
ext2spice cthresh 0.01
ext2spice rthresh 100
ext2spice extresist on
ext2spice subcircuits top on
ext2spice format ngspice
ext2spice -p /foss/designs/PROJECTS/cmos-pll-ihp-sg13g2/Combined_Design/design_data/pex/dff_nclk__dff_nclk/magic_RC -o /foss/designs/PROJECTS/cmos-pll-ihp-sg13g2/Combined_Design/design_data/pex/dff_nclk__dff_nclk/magic_RC/dff_nclk.pex.spice
quit -noprompt
