# Generated by kpex 0.2.5
crashbackups stop
drc off
gds read /foss/designs/PROJECTS/cmos-pll-ihp-sg13g2/Combined_Design/design_data/gds/2bit_freq_divider.gds
load 2bit_freq_divider
select top cell
flatten 2bit_freq_divider_flat
load 2bit_freq_divider_flat
cellname delete 2bit_freq_divider -noprompt
cellname rename 2bit_freq_divider_flat 2bit_freq_divider
select top cell
extract path /foss/designs/PROJECTS/cmos-pll-ihp-sg13g2/Combined_Design/design_data/pex/2bit_freq_divider__2bit_freq_divider/magic_RC
extract do resistance
extract all
ext2sim labels on
ext2sim
extresist tolerance 1
extresist all
ext2spice short none
ext2spice merge none
ext2spice cthresh 0.01
ext2spice rthresh 100
ext2spice extresist on
ext2spice subcircuits top on
ext2spice format ngspice
ext2spice -p /foss/designs/PROJECTS/cmos-pll-ihp-sg13g2/Combined_Design/design_data/pex/2bit_freq_divider__2bit_freq_divider/magic_RC -o /foss/designs/PROJECTS/cmos-pll-ihp-sg13g2/Combined_Design/design_data/pex/2bit_freq_divider__2bit_freq_divider/magic_RC/2bit_freq_divider.pex.spice
quit -noprompt
